apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetings-mongo-depl
spec:
  replicas: 1
  selector: 
    matchLabels:    
      app: meetings-mongo 
  template:   
    metadata:  
      labels:   
        app: meetings-mongo 
    spec: 
      restartPolicy: Always
      containers:
        - name: meetings-mongo
          image: mongo

---
apiVersion: v1
kind: Service
metadata: 
  name: meetings-mongo-srv
spec:
  selector:
    app: meetings-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017


