apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetings-depl
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: meetings 
  template: 
    metadata: 
      labels:
        app: meetings
    spec:   
      containers: 
        - name: meetings
          image: anshadkt/meetings
          env:
            - name: MONGO_URL
              value: mongodb://meetings-mongo-srv/schedulease
            - name: JWT_KEY 
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---  
apiVersion: v1
kind: Service
metadata:
  name: meetings-srv
spec:
  selector:
    app: meetings
  ports:
    - name: meetings
      protocol: TCP
      port: 3000
      targetPort: 3000
