apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetings1-depl
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: meetings1 
  template: 
    metadata: 
      labels:
        app: meetings1
    spec:
      containers:
        - name: meetings1
          image: anshadkt/meetings
          env:
            - name: MONGO_URL
              value: mongodb://meetings1-mongo-srv/schedulease
            - name: JWT_KEY 
              valueFrom: 
                secretKeyRef:
                  name: jwt-secretcode
                  key: JWT_KEY

---  
apiVersion: v1
kind: Service
metadata:
  name: meetings1-srv
spec:
  selector:
    app: meetings1
  ports:
    - name: meetings1
      protocol: TCP
      port: 3000
      targetPort: 3000
