apiVersion: apps/v1
kind: Deployment
metadata:
  name: user1-depl
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: user1 
  template: 
    metadata: 
      labels:
        app: user1
    spec:
      containers:
        - name: user1
          image: anshadkt/user
          env:
            - name: MONGO_URL
              value: mongodb://user1-mongo-srv/schedulease
            - name: JWT_KEY 
              valueFrom: 
                secretKeyRef:
                  name: jwt-secretcode
                  key: JWT_KEY
            - name: NODEPASS 
              valueFrom: 
                secretKeyRef:
                  name: nodepass
                  key: NODEPASS
---  
apiVersion: v1
kind: Service
metadata:
  name: user1-srv
spec:
  selector:
    app: user1
  ports:
    - name: user1
      protocol: TCP
      port: 3000
      targetPort: 3000
