apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: user 
  template: 
    metadata: 
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: anshadkt/userimg
          env:
            - name: MONGO_URL
              value: mongodb://user-mongo-srv/schedulease
            - name: JWT_KEY 
              valueFrom: 
                secretKeyRef:
                  name: jwt-secretcode
                  key: JWT_KEY
            - name: NODEPASS 
              valueFrom: 
                secretKeyRef:
                  name: nodepass
                  key: NODEPASS
---  
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
